name: HeroChat
version: 4.5.0
main: com.herocraftonline.dthielke.herochat.HeroChat
description: Provides fully configurable chat channels.
commands:
  ch:
    description: Lists all HeroChat commands 
    usage: Wrong usage. For help, type /<command> help
  qm:
    description: Sends a quick message to a channel without changing your focus
    usage: /<command> channel message
  leave:
    description: Leaves a channel
    usage: /<command> channel
  join:
    description: Joins a channel
    usage: /<command> channel
  mute:
    description: Mutes a player for a single channel
    usage: /<command> channel player
  gmute:
    description: Globally mutes a player
    usage: /<command> player
