name: HeroChat
version: 3.21
main: com.herocraftonline.dthielke.herochat.HeroChatPlugin
description: Provides fully configurable chat channels.
commands:
  ch:
    description: Lists all HeroChat commands 
    usage: /<command> help
  qm:
    description: Sends a quick message to a channel without changing your focus
    usage: /<command> channel message
    