globals:
    default-channel: Global
channels:
    global:
        Global:
            color: green
            nickname: g
            permissions:
                speak: []
                join: []
            format: '{default}'
            worlds: []
            password: ''
            lists:
                bans: []
                moderators: []
            flags:
                shortcut-allowed: true
                join-messages: false