name: Heroes
main: com.dthielke.herochat.HeroChat
version: 5.0.0
website: http://www.herocraftonline.com
authors: [DThielke]
description: Chat channel system
commands:
  herochat:
    aliases: ['ch']
    description: Root HeroChat command
    usage: /<command>